### ISSUE TITLE
SMTP allows 220-example.com greeting or just 220

### ISSUE THREAD

**Issue by crazy4chrissi** [webdigi/SMTP-Based-Email-Validation#2]
This class expects the SMTP server to greet with "220 ", but "220-" or "220" is also okay as specified by RFC 5321 In Sect. 4.2:

   Greeting       = ( "220 " (Domain / address-literal)
                  [ SP textstring ] CRLF ) /
                  ( "220-" (Domain / address-literal)
                  [ SP textstring ] CRLF
                  *( "220-" [ textstring ] CRLF )
                  "220" [ SP textstring ] CRLF )

i saw servers responding "220" or "220-example", and this class did not accept them. So just remove the space here: 

``` php
 preg_match('/^([0-9]{3}) /ims', $reply, $matches);
```

should be

``` php
 preg_match('/^([0-9]{3})/ims', $reply, $matches);
```

**Comment by webdigi** [comment]
@crazy4chrissi thanks, please submit a pull request.

**Comment by marcelstoer** [comment]
This should be closed because the PR was merged months ago.
